import { StyleSheet, Dimensions } from "react-native";
import { COLORS, FONTS } from "../../theme/theme";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    backButton: {
        position: 'absolute',
        top: 16,
        left: 16,
        zIndex: 10,
    },
    backIcon: {
        fontSize: 28,
        color: COLORS.white,
    },
    content: {
        flex: 1,
        padding: 20,
        paddingTop: 60,
    },
    header: {
        alignItems: 'center',
        marginBottom: 40,
    },
    logo: {
        width: 120,
        height: 120,
        resizeMode: 'contain',
        marginBottom: 20,
    },
    title: {
        ...FONTS.h2,
        color: COLORS.white,
        marginBottom: 8,
    },
    subtitle: {
        ...FONTS.body2,
        color: COLORS.lightGray,
        textAlign: 'center',
        marginHorizontal: 20,
    },
    formContainer: {
        marginBottom: 20,
    },
    inputLabel: {
        ...FONTS.body3,
        color: COLORS.white,
        marginBottom: 8,
        marginTop: 16,
    },
    input: {
        backgroundColor: COLORS.tertiary,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: FONTS.body2.fontSize,
        color: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.gray,
    },
    forgotPasswordButton: {
        alignSelf: 'flex-end',
        marginTop: 12,
        marginBottom: 24,
    },
    forgotPasswordText: {
        ...FONTS.body3,
        color: COLORS.accent,
    },
    loginButton: {
        backgroundColor: COLORS.accent,
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 24,
    },
    loginButtonText: {
        ...FONTS.h4,
        color: COLORS.white,
    },
    registerButton: {
        alignSelf: 'center',
        marginTop: 20,
        paddingVertical: 8,
    },
    registerButtonText: {
        ...FONTS.body3,
        color: COLORS.accent,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 30,
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: COLORS.gray,
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
        width: '48%',
    },
    secondaryButtonText: {
        ...FONTS.body3,
        color: COLORS.white,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        paddingHorizontal: 20,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9999,
    },
    modalContent: {
        backgroundColor: COLORS.secondary,
        borderRadius: 12,
        padding: 24,
        width: width * 0.9,
        maxWidth: 500,
        elevation: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
        alignSelf: 'center',
        margin: 20,
        maxHeight: height * 0.8,
        overflow: 'hidden',
        zIndex: 10000,
    },
    modalTitle: {
        ...FONTS.h3,
        color: COLORS.white,
        marginBottom: 20,
        textAlign: 'center',
        marginTop: 10,
    },
    modalCloseButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        padding: 8,
        zIndex: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 20,
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCloseIcon: {
        fontSize: 24,
        color: COLORS.white,
    },
    formRow: {
        marginBottom: 16,
    },
    formError: {
        color: COLORS.error,
        ...FONTS.body3,
        marginTop: 4,
    },
    passwordStrengthContainer: {
        marginTop: 10,
        marginBottom: 5,
    },
    passwordStrengthBar: {
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 3,
        marginBottom: 6,
    },
    passwordStrengthIndicator: {
        height: '100%',
        borderRadius: 3,
    },
    passwordStrengthText: {
        ...FONTS.body3,
        color: COLORS.lightGray,
        marginBottom: 4,
    },
    passwordHint: {
        ...FONTS.body4,
        color: COLORS.lightGray,
        marginTop: 6,
        marginBottom: 12,
        fontSize: 12,
    },
    modalButton: {
        backgroundColor: COLORS.accent,
        borderRadius: 8,
        paddingVertical: 14,
        alignItems: 'center',
        marginTop: 20,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    modalButtonText: {
        ...FONTS.h4,
        color: COLORS.black,
        fontWeight: 'bold',
    },
    resetText: {
        ...FONTS.body3,
        color: COLORS.lightGray,
        marginBottom: 24,
        textAlign: 'center',
    },
    registerOptionText: {
        ...FONTS.body3,
        color: COLORS.lightGray,
        textAlign: 'center',
        marginTop: 15,
    },
    registerOptionLink: {
        ...FONTS.body3,
        color: COLORS.accent,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
    },
    required: {
        color: COLORS.error,
    },
});
