import { StyleSheet, Dimensions } from "react-native";
import { COLORS, FONTS } from "../../theme/theme";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    header: {
        marginTop: 40,
        marginBottom: 40,
        alignItems: 'center',
    },
    logo: {
        width: 100,
        height: 100,
        resizeMode: 'contain',
        marginBottom: 10,
    },
    title: {
        ...FONTS.h2,
        color: COLORS.white,
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        ...FONTS.body2,
        color: COLORS.lightGray,
        textAlign: 'center',
    },
    formContainer: {
        marginBottom: 20,
    },
    inputLabel: {
        ...FONTS.body3,
        color: COLORS.lightGray,
        marginBottom: 8,
    },
    input: {
        backgroundColor: COLORS.tertiary,
        height: 50,
        borderRadius: 10,
        paddingHorizontal: 15,
        fontSize: 16,
        color: COLORS.white,
        marginBottom: 20,
    },
    agencyListContainer: {
        marginBottom: 20,
    },
    agencyItem: {
        backgroundColor: COLORS.tertiary,
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    selectedAgencyItem: {
        backgroundColor: COLORS.secondary,
        borderWidth: 1,
        borderColor: COLORS.accent,
    },
    agencyName: {
        ...FONTS.body2,
        color: COLORS.white,
    },
    agencyIcon: {
        fontSize: 24,
        color: COLORS.accent,
    },
    selectAgencyButton: {
        backgroundColor: COLORS.tertiary,
        height: 50,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        flexDirection: 'row',
        paddingHorizontal: 15,
    },
    selectAgencyButtonText: {
        ...FONTS.body2,
        color: COLORS.white,
        marginRight: 10,
        flex: 1,
    },
    loginButton: {
        backgroundColor: COLORS.accent,
        height: 50,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    loginButtonText: {
        ...FONTS.h4,
        color: COLORS.background,
    },
    forgotPasswordButton: {
        alignSelf: 'center',
        marginTop: 20,
        paddingVertical: 8,
    },
    forgotPasswordText: {
        ...FONTS.body3,
        color: COLORS.accent,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        paddingHorizontal: 20,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: COLORS.secondary,
        borderRadius: 12,
        padding: 24,
        width: width * 0.9,
        maxWidth: 500,
        elevation: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
        alignSelf: 'center',
        margin: 20,
        maxHeight: height * 0.8,
        overflow: 'hidden',
    },
    modalTitle: {
        ...FONTS.h3,
        color: COLORS.white,
        marginBottom: 20,
        textAlign: 'center',
        marginTop: 10,
    },
    modalCloseButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        padding: 8,
        zIndex: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 20,
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCloseIcon: {
        fontSize: 24,
        color: COLORS.white,
    },
    searchInput: {
        backgroundColor: COLORS.tertiary,
        height: 50,
        borderRadius: 10,
        paddingHorizontal: 15,
        fontSize: 16,
        color: COLORS.white,
        marginBottom: 10,
    },
    agencyListScrollView: {
        maxHeight: height * 0.5,
    },
    noAgencyText: {
        ...FONTS.body2,
        color: COLORS.lightGray,
        textAlign: 'center',
        marginTop: 20,
        padding: 10,
    },
    backButton: {
        position: 'absolute',
        top: 40,
        left: 20,
        zIndex: 10,
    },
    backIcon: {
        color: COLORS.white,
        fontSize: 28,
    },
    agencyList: {
        maxHeight: height * 0.6,
        width: '100%',
    },
    selectedAgencyName: {
        color: COLORS.accent,
        fontWeight: 'bold',
    },
    checkIcon: {
        fontSize: 20,
        color: COLORS.accent,
        marginLeft: 8,
    },
});
